timeout: '18000s'

steps:
  - id: Build NVIDIA Tegra images with edgebuild.yaml
    name: gcr.io/$PROJECT_ID/edgebuild
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'amd64'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/yolov7-training:${BRANCH_NAME}-amd64 -f ./amd64.Dockerfile .
        docker push gcr.io/$PROJECT_ID/yolov7-training:${BRANCH_NAME}-amd64

  - name: 'gcr.io/cloud-builders/docker'
    id: 'manifest'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CLI_EXPERIMENTAL=enabled'
    args:
      - -c
      - |
        docker manifest create \
        gcr.io/$PROJECT_ID/yolov7-training:${BRANCH_NAME}-${SHORT_SHA} \
        gcr.io/$PROJECT_ID/yolov7-training:${BRANCH_NAME}-amd64
      
        docker manifest annotate \
        gcr.io/$PROJECT_ID/yolov7-training:${BRANCH_NAME}-${SHORT_SHA} \
        gcr.io/$PROJECT_ID/yolov7-training:${BRANCH_NAME}-amd64 \
        --os=linux

        docker manifest push gcr.io/$PROJECT_ID/yolov7-training:${BRANCH_NAME}-${SHORT_SHA}
    waitFor: ['amd64']
